# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: psyneulink.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='psyneulink.proto',
  package='psyneulinkviewer',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10psyneulink.proto\x12\x10psyneulinkviewer\"\x0e\n\x0cNullArgument\"P\n\x08Response\x12\x33\n\x08response\x18\x01 \x01(\x0e\x32!.psyneulinkviewer.ResponseMessage\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x17\n\x07PNLPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x19\n\tModelPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1e\n\tGraphJson\x12\x11\n\tmodelJson\x18\x01 \x01(\t*_\n\x0fResponseMessage\x12\x12\n\x0eUP_AND_RUNNING\x10\x00\x12\x0e\n\nMESSAGE_OK\x10\x01\x12\x11\n\rMESSAGE_ERROR\x10\x02\x12\x15\n\x11\x43LOSED_CONNECTION\x10\x03\x32\x99\x01\n\nServeGraph\x12\x42\n\x07LinkPnl\x12\x19.psyneulinkviewer.PNLPath\x1a\x1a.psyneulinkviewer.Response\"\x00\x12G\n\tLoadModel\x12\x1b.psyneulinkviewer.ModelPath\x1a\x1b.psyneulinkviewer.GraphJson\"\x00\x62\x06proto3'
)

_RESPONSEMESSAGE = _descriptor.EnumDescriptor(
  name='ResponseMessage',
  full_name='psyneulinkviewer.ResponseMessage',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UP_AND_RUNNING', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_OK', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MESSAGE_ERROR', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLOSED_CONNECTION', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=220,
  serialized_end=315,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEMESSAGE)

ResponseMessage = enum_type_wrapper.EnumTypeWrapper(_RESPONSEMESSAGE)
UP_AND_RUNNING = 0
MESSAGE_OK = 1
MESSAGE_ERROR = 2
CLOSED_CONNECTION = 3



_NULLARGUMENT = _descriptor.Descriptor(
  name='NullArgument',
  full_name='psyneulinkviewer.NullArgument',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=52,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='psyneulinkviewer.Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response', full_name='psyneulinkviewer.Response.response', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='psyneulinkviewer.Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=134,
)


_PNLPATH = _descriptor.Descriptor(
  name='PNLPath',
  full_name='psyneulinkviewer.PNLPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='psyneulinkviewer.PNLPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=159,
)


_MODELPATH = _descriptor.Descriptor(
  name='ModelPath',
  full_name='psyneulinkviewer.ModelPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='psyneulinkviewer.ModelPath.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=161,
  serialized_end=186,
)


_GRAPHJSON = _descriptor.Descriptor(
  name='GraphJson',
  full_name='psyneulinkviewer.GraphJson',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='modelJson', full_name='psyneulinkviewer.GraphJson.modelJson', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=218,
)

_RESPONSE.fields_by_name['response'].enum_type = _RESPONSEMESSAGE
DESCRIPTOR.message_types_by_name['NullArgument'] = _NULLARGUMENT
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['PNLPath'] = _PNLPATH
DESCRIPTOR.message_types_by_name['ModelPath'] = _MODELPATH
DESCRIPTOR.message_types_by_name['GraphJson'] = _GRAPHJSON
DESCRIPTOR.enum_types_by_name['ResponseMessage'] = _RESPONSEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NullArgument = _reflection.GeneratedProtocolMessageType('NullArgument', (_message.Message,), {
  'DESCRIPTOR' : _NULLARGUMENT,
  '__module__' : 'psyneulink_pb2'
  # @@protoc_insertion_point(class_scope:psyneulinkviewer.NullArgument)
  })
_sym_db.RegisterMessage(NullArgument)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'psyneulink_pb2'
  # @@protoc_insertion_point(class_scope:psyneulinkviewer.Response)
  })
_sym_db.RegisterMessage(Response)

PNLPath = _reflection.GeneratedProtocolMessageType('PNLPath', (_message.Message,), {
  'DESCRIPTOR' : _PNLPATH,
  '__module__' : 'psyneulink_pb2'
  # @@protoc_insertion_point(class_scope:psyneulinkviewer.PNLPath)
  })
_sym_db.RegisterMessage(PNLPath)

ModelPath = _reflection.GeneratedProtocolMessageType('ModelPath', (_message.Message,), {
  'DESCRIPTOR' : _MODELPATH,
  '__module__' : 'psyneulink_pb2'
  # @@protoc_insertion_point(class_scope:psyneulinkviewer.ModelPath)
  })
_sym_db.RegisterMessage(ModelPath)

GraphJson = _reflection.GeneratedProtocolMessageType('GraphJson', (_message.Message,), {
  'DESCRIPTOR' : _GRAPHJSON,
  '__module__' : 'psyneulink_pb2'
  # @@protoc_insertion_point(class_scope:psyneulinkviewer.GraphJson)
  })
_sym_db.RegisterMessage(GraphJson)



_SERVEGRAPH = _descriptor.ServiceDescriptor(
  name='ServeGraph',
  full_name='psyneulinkviewer.ServeGraph',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=318,
  serialized_end=471,
  methods=[
  _descriptor.MethodDescriptor(
    name='LinkPnl',
    full_name='psyneulinkviewer.ServeGraph.LinkPnl',
    index=0,
    containing_service=None,
    input_type=_PNLPATH,
    output_type=_RESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadModel',
    full_name='psyneulinkviewer.ServeGraph.LoadModel',
    index=1,
    containing_service=None,
    input_type=_MODELPATH,
    output_type=_GRAPHJSON,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVEGRAPH)

DESCRIPTOR.services_by_name['ServeGraph'] = _SERVEGRAPH

# @@protoc_insertion_point(module_scope)
