# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import psyneulink_pb2 as psyneulink__pb2


class ServeGraphStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LinkPnl = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/LinkPnl',
                request_serializer=psyneulink__pb2.PNLPath.SerializeToString,
                response_deserializer=psyneulink__pb2.Response.FromString,
                )
        self.LoadModel = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/LoadModel',
                request_serializer=psyneulink__pb2.ModelPath.SerializeToString,
                response_deserializer=psyneulink__pb2.GraphJson.FromString,
                )


class ServeGraphServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LinkPnl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServeGraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LinkPnl': grpc.unary_unary_rpc_method_handler(
                    servicer.LinkPnl,
                    request_deserializer=psyneulink__pb2.PNLPath.FromString,
                    response_serializer=psyneulink__pb2.Response.SerializeToString,
            ),
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=psyneulink__pb2.ModelPath.FromString,
                    response_serializer=psyneulink__pb2.GraphJson.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'psyneulinkviewer.ServeGraph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServeGraph(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LinkPnl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/LinkPnl',
            psyneulink__pb2.PNLPath.SerializeToString,
            psyneulink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/LoadModel',
            psyneulink__pb2.ModelPath.SerializeToString,
            psyneulink__pb2.GraphJson.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
