# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import stubs.psyneulink_pb2 as psyneulink__pb2


class ServeGraphStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModel = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/LoadModel',
                request_serializer=psyneulink__pb2.ModelPath.SerializeToString,
                response_deserializer=psyneulink__pb2.GraphJson.FromString,
                )
        self.UpdateModel = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/UpdateModel',
                request_serializer=psyneulink__pb2.GraphJson.SerializeToString,
                response_deserializer=psyneulink__pb2.Response.FromString,
                )
        self.RunModel = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/RunModel',
                request_serializer=psyneulink__pb2.InputJson.SerializeToString,
                response_deserializer=psyneulink__pb2.Response.FromString,
                )
        self.PNLApi = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/PNLApi',
                request_serializer=psyneulink__pb2.PNLJson.SerializeToString,
                response_deserializer=psyneulink__pb2.PNLJson.FromString,
                )
        self.SaveModel = channel.unary_unary(
                '/psyneulinkviewer.ServeGraph/SaveModel',
                request_serializer=psyneulink__pb2.ModelData.SerializeToString,
                response_deserializer=psyneulink__pb2.Response.FromString,
                )


class ServeGraphServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LoadModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PNLApi(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServeGraphServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModel': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModel,
                    request_deserializer=psyneulink__pb2.ModelPath.FromString,
                    response_serializer=psyneulink__pb2.GraphJson.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=psyneulink__pb2.GraphJson.FromString,
                    response_serializer=psyneulink__pb2.Response.SerializeToString,
            ),
            'RunModel': grpc.unary_unary_rpc_method_handler(
                    servicer.RunModel,
                    request_deserializer=psyneulink__pb2.InputJson.FromString,
                    response_serializer=psyneulink__pb2.Response.SerializeToString,
            ),
            'PNLApi': grpc.unary_unary_rpc_method_handler(
                    servicer.PNLApi,
                    request_deserializer=psyneulink__pb2.PNLJson.FromString,
                    response_serializer=psyneulink__pb2.PNLJson.SerializeToString,
            ),
            'SaveModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveModel,
                    request_deserializer=psyneulink__pb2.ModelData.FromString,
                    response_serializer=psyneulink__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'psyneulinkviewer.ServeGraph', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServeGraph(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LoadModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/LoadModel',
            psyneulink__pb2.ModelPath.SerializeToString,
            psyneulink__pb2.GraphJson.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/UpdateModel',
            psyneulink__pb2.GraphJson.SerializeToString,
            psyneulink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/RunModel',
            psyneulink__pb2.InputJson.SerializeToString,
            psyneulink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PNLApi(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/PNLApi',
            psyneulink__pb2.PNLJson.SerializeToString,
            psyneulink__pb2.PNLJson.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SaveModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/psyneulinkviewer.ServeGraph/SaveModel',
            psyneulink__pb2.ModelData.SerializeToString,
            psyneulink__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
