# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: psyneulink.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10psyneulink.proto\x12\x10psyneulinkviewer\"\x0e\n\x0cNullArgument\",\n\tModelData\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x11\n\tmodelJson\x18\x02 \x01(\t\"P\n\x08Response\x12\x33\n\x08response\x18\x01 \x01(\x0e\x32!.psyneulinkviewer.ResponseMessage\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x19\n\tModelPath\x12\x0c\n\x04path\x18\x01 \x01(\t\"\x1e\n\tGraphJson\x12\x11\n\tmodelJson\x18\x01 \x01(\t\"\x1e\n\x07PNLJson\x12\x13\n\x0bgenericJson\x18\x01 \x01(\t\"6\n\tInputJson\x12\x16\n\x0e\x65xecutableNode\x18\x01 \x01(\t\x12\x11\n\tinputData\x18\x02 \x01(\t*_\n\x0fResponseMessage\x12\x12\n\x0eUP_AND_RUNNING\x10\x00\x12\x0e\n\nMESSAGE_OK\x10\x01\x12\x11\n\rMESSAGE_ERROR\x10\x02\x12\x15\n\x11\x43LOSED_CONNECTION\x10\x03\x32\xbc\x03\n\nServeGraph\x12G\n\tLoadModel\x12\x1b.psyneulinkviewer.ModelPath\x1a\x1b.psyneulinkviewer.GraphJson\"\x00\x12H\n\x0bUpdateModel\x12\x1b.psyneulinkviewer.GraphJson\x1a\x1a.psyneulinkviewer.Response\"\x00\x12\x45\n\x08RunModel\x12\x1b.psyneulinkviewer.InputJson\x1a\x1a.psyneulinkviewer.Response\"\x00\x12@\n\x06PNLApi\x12\x19.psyneulinkviewer.PNLJson\x1a\x19.psyneulinkviewer.PNLJson\"\x00\x12\x46\n\tSaveModel\x12\x1b.psyneulinkviewer.ModelData\x1a\x1a.psyneulinkviewer.Response\"\x00\x12J\n\nStopServer\x12\x1e.psyneulinkviewer.NullArgument\x1a\x1a.psyneulinkviewer.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'psyneulink_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RESPONSEMESSAGE']._serialized_start=329
  _globals['_RESPONSEMESSAGE']._serialized_end=424
  _globals['_NULLARGUMENT']._serialized_start=38
  _globals['_NULLARGUMENT']._serialized_end=52
  _globals['_MODELDATA']._serialized_start=54
  _globals['_MODELDATA']._serialized_end=98
  _globals['_RESPONSE']._serialized_start=100
  _globals['_RESPONSE']._serialized_end=180
  _globals['_MODELPATH']._serialized_start=182
  _globals['_MODELPATH']._serialized_end=207
  _globals['_GRAPHJSON']._serialized_start=209
  _globals['_GRAPHJSON']._serialized_end=239
  _globals['_PNLJSON']._serialized_start=241
  _globals['_PNLJSON']._serialized_end=271
  _globals['_INPUTJSON']._serialized_start=273
  _globals['_INPUTJSON']._serialized_end=327
  _globals['_SERVEGRAPH']._serialized_start=427
  _globals['_SERVEGRAPH']._serialized_end=871
# @@protoc_insertion_point(module_scope)
