name: Installers
on:
  release:
    types:
      - created
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        platform: ['darwin/x64', 'darwing/arm64', 'linux/x64']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.12.7

    - name: Install dependencies
      working-directory: ./package/installers
      run: pip install -r requirements.txt
    - name: Build
      working-directory: ./package/installers
      run: pyinstaller --onefile installer.py
    - name: Rename the installer with the OS name
      working-directory: ./package/installers
      run: mv dist/installer dist/installer-${{ matrix.platform == 'darwin/x64' && 'osx-x64' || matrix.platform == 'darwin/arm64' && 'osx-arm64' || matrix.platform == 'linux/x64' && 'linux-x64' }}
    - name: release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./package/installers/dist/installer-${{ matrix.platform == 'darwin/x64' && 'osx-x64' || matrix.platform == 'darwin/arm64' && 'osx-arm64' || matrix.platform == 'linux/x64' && 'linux-x64' }}
